[package]
name = "patissier"
version = "0.1.0"
authors = ["riku.okajima <riku.okajima@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
